- hosts: all
  gather_facts: no

  tasks:
  # -------------------  Configure hostname  ------------------- # 
  - name: Configure hostname
    become: true
    copy:
      content: |
        pi-thinclient
      dest: /etc/hostname
      backup: yes
    tags:
      - pi_config
      - hostname

  # -------------------  Configure hosts  ------------------- # 
  - name: Configure hosts
    become: true
    copy:
      content: |
        127.0.0.1	localhost pi-thinclient
        ::1		localhost ip6-localhost ip6-loopback
        ff02::1		ip6-allnodes
        ff02::2		ip6-allrouters
      dest: /etc/hosts
    tags:
      - pi_config
      - hosts

  # -------------------  Configure ultrawide monitor  ------------------- # 
  - name: Configure ultrawide monitor
    become: true
    blockinfile:
      path: /boot/config.txt
      insertafter: EOF
      block: |
        #
        # config for ultrawide monitor 2560x1080
        hdmi_drive=2
        hdmi_ignore_edid=0xa5000080
        hdmi_group=2
        hdmi_mode=87
        hdmi_aspect_21_9=7
        hdmi_pixel_freq_limit=400000000
        hdmi_cvt=2560 1080 50 7 0 0 1
        #config_hdmi_boost=4
        max_framebuffer_width=2560
        max_framebuffer_height=1080
        framebuffer_width=2560
        framebuffer_height=1080
    tags:
      - pi_config
      - ultrawide_monitor
        
  # -------------------  Install packages  ------------------- # 
  - name: Install packages
    become: true
    apt:
      update_cache: yes
      autoremove: yes
      state: present
      pkg:
        - vim
        - zulumount-cli
        - screen
        - encfs
        - fish
        - firefox-esr
        - vlc
        - keepassxc
        - remmina
        - kodi 

    tags:
      - install_pkgs



  # ------------------- configure fish ------------------- # 
  - name: set fish as default shell
    become: true
    shell: chsh -s /usr/bin/fish
    tags:
      - fish

  - name: Create fish config dir
    file:
      dest: ~/.config/fish
      state: directory
    tags:
      - fish

  - name: Configure fish
    copy:
      dest: ~/.config/fish/config.fish
      content: |
        set -g -x fish_greeting 'This raspberry pi is a property of Poomalairaj. Unauthorized access is prohibited'
    tags:
      - fish
